### ISSUE TITLE
Store release files in different branches

### ISSUE THREAD

**Issue by mcquenji** [codecollabspace/chatgpt_diploma_citation_extension#11]
I'd store the zipped files in different branches instead of the main branch as that's kinda distracting imo. perhaps a `chrome ` branch where the generated files for the chrome release reside and the same for firefox on a `firefox` branch?

**Comment by mcquenji** [comment]
noticed we already have different branches for chrome and firefox, why not use them for the zipped files also?

**Comment by officialbishowb** [comment]
Initial thought was it wouble be easier , but now it makes more sense to push to the browser branch.
