### ISSUE TITLE
Latex code inside the prompt

### ISSUE THREAD

**Issue by mcquenji** [codecollabspace/chatgpt_diploma_citation_extension#5]
When latex code is present inside the prompt and you paste the citation into bibtex, it will try to interpret the latex code and most likely throw an error. if it doesn't throw you'll have subheadings in your references like this:

![image](https://github.com/codecollabspace/chatgpt_diploma_citation_extension/assets/60017181/802907ef-1d04-460a-bd3f-f4d32ee8cc13)

beautiful isn't it :)

---

we should escape characters with the following snippet:

```js
function escapeLaTeX(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/~/g, '\\~')
    .replace(/\^/g, '\\^')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/{/g, '\\{')
    .replace(/}/g, '\\}');
}
```

**Comment by officialbishowb** [comment]
escapeLaTeX has been added. Apparently it works if you add \textbackslash before any latex code.
